import React from 'react';
import { Container } from '@/components/ui/Container';
import { SectionHeading } from '@/components/ui/SectionHeading';
import { Badge } from '@/components/ui/Badge';
import { Card } from '@/components/ui/Card';
import { Brain, ShieldAlert, CheckCircle2, ArrowRight, Activity, Terminal } from 'lucide-react';

export const ExplainableAiSection: React.FC = () => {
  return (
    <section className="py-24 bg-slate-950/90 border-t border-slate-900 relative" id="explainable-ai">
      <Container size="xl">
        <SectionHeading
          badge="EXPLAINABLE AI (XAI)"
          title="Security Intelligence You Can Trust"
          subtitle="Unlike black-box anomaly detectors, Spy-fi provides detailed context, evidence indicators, and confidence scoring for every alert."
        />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          {/* Left Column: Explanation Text & Feature Highlights */}
          <div className="lg:col-span-5 space-y-6">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-emerald-950/80 border border-emerald-700/60 flex items-center justify-center text-emerald-400">
                <Brain className="h-5 w-5" />
              </div>
              <h3 className="text-xl font-bold text-white">Transparent Alert Reasoning</h3>
            </div>

            <p className="text-sm text-slate-300 leading-relaxed">
              Every cybersecurity alert generated by Spy-fi is accompanied by clear natural language explanations and quantifiable evidence parameters so SOC analysts can make split-second decisions without second-guessing model predictions.
            </p>

            <ul className="space-y-3">
              {[
                'Quantified Risk Score (0-100) and AI Confidence Percentage',
                'Exact traffic indicators that triggered the anomaly classifier',
                'Comparison against historical normal baseline traffic metrics',
                'Actionable SOC remediation steps provided immediately',
              ].map((item, idx) => (
                <li key={idx} className="flex items-start gap-2.5 text-xs text-slate-300">
                  <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>

            <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 text-xs font-mono text-slate-400">
              <span className="text-emerald-400 font-bold block mb-1">FastAPI Backend Contract:</span>
              <p className="text-[11px] text-slate-400">
                Returns standardized JSON with prediction, threat_type, confidence, anomaly_score, explanation, and recommended_action.
              </p>
            </div>
          </div>

          {/* Right Column: Interactive Mock Threat Analysis Card */}
          <div className="lg:col-span-7">
            <div className="rounded-2xl bg-slate-950 border border-slate-800 p-6 sm:p-8 shadow-2xl relative overflow-hidden">
              
              {/* Card Top Banner */}
              <div className="flex flex-wrap items-center justify-between gap-4 pb-6 mb-6 border-b border-slate-800/80">
                <div className="flex items-center gap-3">
                  <div className="h-9 w-9 rounded-lg bg-orange-950/80 border border-orange-700/60 flex items-center justify-center text-orange-400">
                    <ShieldAlert className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-slate-400">ALERT ID: THREAT-8492</span>
                      <Badge severity="HIGH" size="sm" dot />
                    </div>
                    <h4 className="text-lg font-bold text-white mt-0.5">PORT SCAN DETECTED</h4>
                  </div>
                </div>

                <div className="flex items-center gap-6">
                  <div className="text-right">
                    <span className="text-[10px] font-mono text-slate-400 uppercase block">AI CONFIDENCE</span>
                    <span className="text-lg font-mono font-bold text-emerald-400">94.7%</span>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] font-mono text-slate-400 uppercase block">RISK SCORE</span>
                    <span className="text-lg font-mono font-bold text-orange-400">87 / 100</span>
                  </div>
                </div>
              </div>

              {/* Target Details Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6 font-mono text-xs">
                <div className="p-2.5 rounded bg-slate-900 border border-slate-800">
                  <span className="text-[10px] text-slate-500 block">SOURCE IP</span>
                  <span className="text-slate-200 font-semibold">192.168.1.25</span>
                </div>
                <div className="p-2.5 rounded bg-slate-900 border border-slate-800">
                  <span className="text-[10px] text-slate-500 block">DESTINATION IP</span>
                  <span className="text-slate-200 font-semibold">10.0.0.12</span>
                </div>
                <div className="p-2.5 rounded bg-slate-900 border border-slate-800">
                  <span className="text-[10px] text-slate-500 block">PORTS CONTACTED</span>
                  <span className="text-slate-200 font-semibold">41 Ports</span>
                </div>
                <div className="p-2.5 rounded bg-slate-900 border border-slate-800">
                  <span className="text-[10px] text-slate-500 block">DURATION</span>
                  <span className="text-slate-200 font-semibold">12.4s</span>
                </div>
              </div>

              {/* Why Flagged Section */}
              <div className="mb-6 p-4 rounded-xl bg-slate-900/60 border border-slate-800">
                <h5 className="text-xs font-mono font-bold text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-2">
                  <Terminal className="h-4 w-4 text-emerald-400" /> WHY WAS THIS FLAGGED?
                </h5>
                <ul className="space-y-2 text-xs text-slate-300">
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-orange-400" />
                    <span><strong className="text-white">327 connection attempts</strong> initiated within 12.4s interval</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-orange-400" />
                    <span>Targeted <strong className="text-white">41 unique destination ports</strong> in sequential pattern</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-orange-400" />
                    <span>Request frequency exceeded normal threshold by <strong className="text-white">410%</strong></span>
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-orange-400" />
                    <span>Significant statistical deviation from historical baseline (Z-score 4.8)</span>
                  </li>
                </ul>
              </div>

              {/* Recommended Action */}
              <div className="p-4 rounded-xl bg-emerald-950/30 border border-emerald-800/60 flex items-start gap-3">
                <CheckCircle2 className="h-5 w-5 text-emerald-400 shrink-0 mt-0.5" />
                <div>
                  <h6 className="text-xs font-mono font-bold text-emerald-400 uppercase">RECOMMENDED SOC ACTION</h6>
                  <p className="text-xs text-slate-300 mt-1">
                    Investigate source host 192.168.1.25 and review subsequent unidirectional traffic originating from the same source.
                  </p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </Container>
    </section>
  );
};
